{
  parserClass="de.docksnet.puml.parser.PumlParser"
  stubParserClass="de.docksnet.puml.parser.GrammarParserUtil"

  implements="de.docksnet.puml.psi.BnfCompositeElement"
  extends="de.docksnet.puml.psi.impl.BnfCompositeElementImpl"

  psiClassPrefix="Bnf"
  psiImplClassSuffix="Impl"
  psiPackage="de.docksnet.puml.psi"
  psiImplPackage="de.docksnet.puml.psi.impl"
  psiImplUtilClass="de.docksnet.puml.psi.impl.GrammarPsiImplUtil"

  elementTypeHolderClass="de.docksnet.puml.psi.BnfTypes"
  elementTypePrefix="BNF_"
  elementTypeClass="de.docksnet.puml.psi.BnfCompositeElementType"
  tokenTypeClass="de.docksnet.puml.psi.BnfTokenType"
  
  tokens = [
    START_UML="@startuml"
    END_UML="@enduml"
    ACTOR="actor"
    DASH="-"
  ]

}

root ::= "@startuml"